### ISSUE TITLE
Log key-up and key-down events?

### ISSUE THREAD

**Issue by resuna** [Ga68/benign-key-logger#16]
Logging key-up and key-down events independently would be useful for debugging my mechanical keyboard's QMK programming.

**Comment by resuna** [comment]
[patch.txt](https://github.com/user-attachments/files/16692036/patch.txt)

**Comment by resuna** [comment]
PS: You might want to make that constant default to False.

**Comment by Ga68** [comment]
another good idea
done https://github.com/Ga68/benign-key-logger/commit/9807c2ad3528d7cedc1b0c91dc2cbba4b3e01f31
