### ISSUE TITLE
Add a mode that doesn't track space/backspace + letter n-grams

### ISSUE THREAD

**Issue by molohov** [Ga68/benign-key-logger#9]
These n-grams dominate the statistics and make searching for meaningful n-grams difficult.

**Comment by Ga68** [comment]
I'm going to close this as the particular request I think is covered by the SQL (which if you're not following, just let me know and I can spell it out more for you, not a worry), and I don't think that implementing it into the main code base makes sense. However, I'm going to track [the ability to use an ignore list on a new issue](https://github.com/Ga68/benign-key-logger/issues/10) you may want to go follow. I think that's a good addition.

**Comment by Ga68** [comment]
See the comment in the new issue. This has been resolved.
https://github.com/Ga68/benign-key-logger/issues/10#issuecomment-908622933
